server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/appleg1226/spring-cloud-msa-config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/