spring:
  profiles:
    active: server1

  rabbitmq:
    host: localhost
    port: 5672
    username: eunchong
    password: dmschd92

  cloud:
    stream:
      bindings:
        input:
          destination: buyItems
          group: buyItemsQueue

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


---
spring:
  profiles: server1
  application:
    name: user-service

server:
  port: 8083


---
spring:
  profiles: server2
  application:
    name: user-service

server:
  port: 8084