spring:
  profiles:
    active: server1

---
spring:
  profiles: server1
  application:
    name: shop-service

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: server2
  application:
    name: shop-service

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
