spring:
  profiles:
    active: server1

  rabbitmq:
    host: localhost
    port: 5672
    username: eunchong
    password: dmschd92

  cloud:
    stream:
      bindings:
        buyItemChannel:
          destination: buyItems
      default:
        contentType: application/json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/




---
spring:
  profiles: server1
  application:
    name: shop-service

server:
  port: 8081

---
spring:
  profiles: server2
  application:
    name: shop-service

server:
  port: 8082
