server:
  port: 8080

eureka:
  client:
    registerWithEureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  retryable: true
  routes:
    shop:
      path: /shop/**
      serviceId: shop-service
    user:
      path: /user/**
      serviceId: user-service

logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace

spring:
  application:
    name: gateway-service
  zipkin:
    baseUrl: http://localhost:9411/